version: "3.7"

services:
  redis:
    image: redis:5-alpine
    deploy:
      mode: global
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
