version: "3.7"

services:
  redis:
    image: redis:5-alpine
    deploy:
      mode: global
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  object-store:
    image: blesswinsamuel/object-store:latest
    deploy:
      replicas: 1
    environment:
      PORT: 80
